### PR TITLE
Feature/strapi server: API implemented

### PR DESCRIPTION
**Pull request by surajsharma**
The Strapi documentation explains how to create a custom route for the API [here](https://strapi.io/documentation/v3.x/concepts/routing.html#how-to-create-a-route), however in following their example, the API returns HTTP 500 errors with the backend throwing up:
`error AssertionError [ERR_ASSERTION]: status code must be a number`

### CODE REVIEW

**Comment by dennyabrain** [comment]
@surajsharma do you need my help in clearing the PR? It would be ideal if the PR and commits only had the files changed for THIS feature

**Comment by surajsharma** [comment]
> @surajsharma do you need my help in clearing the PR? It would be ideal if the PR and commits only had the files changed for THIS feature

no i think i have figured it out, i don't understand why the index.js file keeps popping up in the commit causing conflicts, if you could look into that it'd be great. this can be closed.

**Comment by dennyabrain** [comment]
Hi @surajsharma some feedback and questions

	1. in config/routes.json, only add the NEW routes. You don’t have to redefine the default routes
 	2. rename the following routes as shown
		1. /messages/bygroupid/:groupid -> /messages/groups/:id
		2. /messages/byid/:msgid -> /messages/:id
			also, not sure what you are trying to do anything custom here, but if you just want to get a message by its id, it should be builtin by default. try doing a GET request to /messages/:id and see if it serves your purpose
	3. Can you elaborate what the settings in src/api/api/message/models/message.settings.json do?
	4. Same feedback as 1 for the tag routes in src/api/api/tag/config/routes.json
	5. Same feedback as 1 for WhatsApp-group routes in src/api/api/whatsapp-group/config/routes.json

I am a bit concerned about the changes in src/scraper/index.js. It looks like this PR will delete the content of that file. as long as you have a local back up of the content of that file, I am fine with merging this PR without resolving the issue.

**Comment by surajsharma** [comment]
@dennyabrain 
1) I am (was?) under the impression that writing a custom route is faster than deep filtering, hence the custom route for default endpoints.

2) Again, is writing a custom route by itself faster than deep filtering? Strapi does not seem to throw a warning when I get the data via custom route vs. via deep filter on the default endpoint.

3) This is metadata describing the db model, if changed, will cause the server to recreate the model as per the JSON i think, haven't used it since I am testing with the Strapi front-end itself, which generates this file.

4) and 5) If you really don't think consuming the endpoints in this fashion is advantageous, I will revert to defaults.

Accidentally did a  `git rm` on the `index.js` file have added it back to the repo. my bad.

**Pull request merged**
